In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df1=pd.read_excel(r"Original_database.xlsx",sheet_name="Ti-Cs")

In [3]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):
    if not isinstance(desc, str):
        return None
    mat = np.zeros((4, 7), dtype=int)
    
    if desc.strip() == '16Cs':
        for r, c in pos_map.values():
            mat[r, c] = 1
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2 
        else:
            mat[r, c] = 1 
    return mat

df1['Matrix'] = df1['M1-M2'].apply(catalyst_to_matrix)

In [4]:
df1

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,16Cs,0.0,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
1,1Ti-1,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
2,2Ti14Cs-1+6,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 2, 1, 1, 0, 0],..."
3,2Ti14Cs-1+7,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 2, 1, 0, 0],..."
4,2Ti14Cs-1+10,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
...,...,...,...,...
5613,15Ti1Cs-1+2+3+4+5+6+7+8+9+10+11+13+14+15+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
5614,15Ti1Cs-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
5615,15Ti1Cs-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
5616,15Ti1Cs-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
5617,15Ti1Cs-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."

In [5]:
df2=pd.read_excel(r"Original_database.xlsx",sheet_name="Cs-Si")

In [6]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):
    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Si':
        for r, c in pos_map.values():
            mat[r, c] = 3
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 1  
        else:
            mat[r, c] = 3  

    return mat


df2['Matrix'] = df2['M1-M2'].apply(catalyst_to_matrix)

In [7]:
df2

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,16Si,0.000000,1,"[[3, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,1Cs15Si-1,0.000000,1,"[[1, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,2Cs14Si-1+2,0.046875,3,"[[1, 1, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,2Cs14Si-1+4,0.046875,3,"[[1, 3, 3, 1, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
4,2Cs14Si-1+5,0.046875,3,"[[1, 3, 3, 3, 0, 0, 0], [0, 1, 3, 3, 3, 0, 0],..."
...,...,...,...,...
4109,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+13+14+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4110,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4111,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4112,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4113,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."

In [8]:
df3=pd.read_excel(r"Original_database.xlsx",sheet_name="Ti-Si")

In [9]:
import numpy as np
import re

pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):

    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Ti':
        for r, c in pos_map.values():
            mat[r, c] = 2
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2   
        else:
            mat[r, c] = 3   

    return mat


df3['Matrix'] = df3['M1-M2'].apply(catalyst_to_matrix)

In [10]:
df3

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,1Ti15Si-1,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,2Ti14Si-1+2,0,1,"[[2, 2, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,2Ti14Si-1+4,0,1,"[[2, 3, 3, 2, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,2Ti14Si-1+5,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 2, 3, 3, 3, 0, 0],..."
4,2Ti14Si-1+8,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 2, 0, 0],..."
...,...,...,...,...
4245,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4246,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4247,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4248,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4249,16Ti,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."

In [11]:
df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

In [12]:
df

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,16Cs,0.0,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
1,1Ti-1,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
2,2Ti14Cs-1+6,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 2, 1, 1, 0, 0],..."
3,2Ti14Cs-1+7,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 2, 1, 0, 0],..."
4,2Ti14Cs-1+10,0.0,1,"[[2, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
...,...,...,...,...
13977,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
13978,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
13979,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
13980,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
13981,16Ti,0.0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."

In [13]:
import os
import ast
import random
import numpy as np
import pandas as pd

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_DISABLE_MKL'] = '1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Conv2D, MaxPooling2D, Dense, Concatenate, Dropout,
    GlobalAveragePooling2D
)
from tensorflow.keras.callbacks import ReduceLROnPlateau, LearningRateScheduler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

N_SPLITS = 5
BATCH_SIZE = 32
EPOCHS = 100
NUM_CLASSES = 4
RANDOM_STATE = SEED
EXPECTED_SHAPE = (4, 7)
L2 = 1e-4
DROPOUT = 0.3
INIT_LR = 1e-3

REDUCE_LR_CALLBACK = ReduceLROnPlateau(
    monitor='val_loss', factor=0.5, patience=8, min_lr=1e-6
)

def create_adaptive_lr_schedule(initial_lr=INIT_LR):
    def lr_schedule(epoch):
        if epoch < 30:
            return initial_lr
        elif epoch < 60:
            return initial_lr * 0.3
        elif epoch < 80:
            return initial_lr * 0.2
        else:
            return initial_lr * 0.1
    return LearningRateScheduler(lr_schedule)

def parse_matrix_cell(cell):
    if isinstance(cell, np.ndarray):
        return cell
    if isinstance(cell, list):
        return np.array(cell)
    if isinstance(cell, (int, float)):
        return np.array([[cell]])
    if isinstance(cell, str):
        try:
            return np.array(ast.literal_eval(cell))
        except:
            parts = [float(x) for x in cell.replace(';', ',').split(',') if x.strip() != '']
            return np.array(parts)
    raise ValueError(f"Unsupported Matrix cell type: {type(cell)}")

def dataset_to_Xy(dataset):
    X = np.stack([parse_matrix_cell(x).reshape(EXPECTED_SHAPE) for x in dataset['Matrix']], axis=0)[..., np.newaxis]
    y_raw = dataset['True Class'].astype(int).values
    return X, y_raw

def build_model_improved():
    from tensorflow.keras.layers import LeakyReLU

    inp = Input(shape=(4,7,1))

    x1 = Conv2D(96, (1,5), padding='same', kernel_regularizer=regularizers.l2(L2))(inp)
    x1 = LeakyReLU(0.1)(x1)

    x2 = Conv2D(128, (1,5), padding='same', kernel_regularizer=regularizers.l2(L2))(x1)
    x2 = LeakyReLU(0.1)(x2)
    x2 = Concatenate()([x1, x2])

    x3 = Conv2D(128, (1,5), padding='same', kernel_regularizer=regularizers.l2(L2))(x2)
    x3 = LeakyReLU(0.1)(x3)
    x3 = Concatenate()([x1, x2, x3])

    x = MaxPooling2D((1,2))(x3)

    x = Conv2D(256, (2,2), padding='valid', kernel_regularizer=regularizers.l2(L2))(x)
    x = LeakyReLU(0.1)(x)

    x = GlobalAveragePooling2D()(x)

    x = Dense(1024, kernel_regularizer=regularizers.l2(L2))(x)
    x = LeakyReLU(0.1)(x)
    x = Dropout(DROPOUT)(x)

    x = Dense(512, kernel_regularizer=regularizers.l2(L2))(x)
    x = LeakyReLU(0.1)(x)
    x = Dropout(DROPOUT)(x)

    out = Dense(NUM_CLASSES, activation='softmax')(x)

    model = Model(inp, out)
    model.compile(optimizer=Adam(INIT_LR), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def run_cv_and_plot(dataset):
    X, y_raw = dataset_to_Xy(dataset)
    y0 = (y_raw - 1).astype(int)
    y_cat = to_categorical(y0, NUM_CLASSES)

    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

    y_pred_full = np.zeros(len(dataset), dtype=int)
    y_score_full = np.zeros((len(dataset), NUM_CLASSES))

    accs = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X, y0), 1):
        print(f"Fold {fold}")

        model = build_model_improved()

        model.fit(
            X[train_idx], y_cat[train_idx],
            validation_data=(X[test_idx], y_cat[test_idx]),
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            callbacks=[create_adaptive_lr_schedule(), REDUCE_LR_CALLBACK],
            verbose=0
        )

        preds = model.predict(X[test_idx], verbose=0)
        labels = np.argmax(preds, axis=1)

        y_pred_full[test_idx] = labels
        y_score_full[test_idx] = preds

        acc = accuracy_score(np.argmax(y_cat[test_idx], axis=1), labels)
        accs.append(acc)
        print(f"Fold accuracy: {acc}")

    print("Per-fold accuracy:", accs)

    overall_acc = accuracy_score(y0, y_pred_full)
    print(f"Overall accuracy: {overall_acc}")

    oof_df = pd.DataFrame({
        'True_Class': y_raw,
        'Predicted_Class': y_pred_full + 1
    })

    for i in range(NUM_CLASSES):
        oof_df[f'prob_class_{i+1}'] = y_score_full[:, i]

    oof_df['Matrix'] = dataset['Matrix'].astype(str)

    oof_df.to_csv("CV result.csv", index=False)
    print("Saved as CV result.csv")

if __name__ == "__main__":
    run_cv_and_plot(df)

Fold 1
Fold accuracy: 0.9585269932070075
Fold 2
Fold accuracy: 0.960672148730783
Fold 3
Fold accuracy: 0.9603004291845494
Fold 4
Fold accuracy: 0.959585121602289
Fold 5
Fold accuracy: 0.9610157367668097
Per-fold accuracy: [0.9585269932070075, 0.960672148730783, 0.9603004291845494, 0.959585121602289, 0.9610157367668097]
Overall accuracy: 0.9600200257473895
Saved as CV result.csv

In [14]:
result=pd.read_csv(r"CV result.csv")

In [15]:
result

,True_Class,Predicted_Class,prob_class_1,prob_class_2,prob_class_3,prob_class_4,Matrix
0,1,1,1.000000,1.557611e-11,2.003883e-24,6.429623e-23,[[1 1 1 1 0 0 0]\n [0 1 1 1 1 0 0]\n [0 0 1 1 ...
1,1,1,1.000000,6.542828e-09,3.326383e-22,4.622985e-14,[[2 1 1 1 0 0 0]\n [0 1 1 1 1 0 0]\n [0 0 1 1 ...
2,1,1,0.999998,2.159674e-06,6.482875e-17,7.269328e-14,[[2 1 1 1 0 0 0]\n [0 1 2 1 1 0 0]\n [0 0 1 1 ...
3,1,1,1.000000,1.544568e-07,1.096045e-17,5.244432e-12,[[2 1 1 1 0 0 0]\n [0 1 1 2 1 0 0]\n [0 0 1 1 ...
4,1,1,0.999998,1.994562e-06,1.202553e-14,1.162846e-07,[[2 1 1 1 0 0 0]\n [0 1 1 1 1 0 0]\n [0 0 1 2 ...
...,...,...,...,...,...,...,...
13977,1,1,1.000000,5.786899e-14,7.518559e-14,1.169927e-29,[[2 2 2 2 0 0 0]\n [0 2 2 2 2 0 0]\n [0 0 2 2 ...
13978,1,1,1.000000,1.524155e-15,2.447295e-11,2.888258e-30,[[2 2 2 2 0 0 0]\n [0 2 2 2 2 0 0]\n [0 0 2 2 ...
13979,1,1,1.000000,1.268567e-15,1.930222e-11,1.606761e-30,[[2 2 2 2 0 0 0]\n [0 2 2 2 2 0 0]\n [0 0 2 2 ...
13980,1,1,1.000000,9.461635e-16,1.508028e-11,1.185239e-30,[[2 2 2 2 0 0 0]\n [0 2 2 2 2 0 0]\n [0 0 2 2 ...
13981,1,1,1.000000,4.886416e-17,2.586260e-14,1.464910e-31,[[2 2 2 2 0 0 0]\n [0 2 2 2 2 0 0]\n [0 0 2 2 ...

In [23]:
exp=result.iloc[:,0]

In [24]:
exp

0        1
1        1
2        1
3        1
4        1
        ..
13977    1
13978    1
13979    1
13980    1
13981    1
Name: True_Class, Length: 13982, dtype: int64

In [25]:
pre=result.iloc[:,1]

In [26]:
pre

0        1
1        1
2        1
3        1
4        1
        ..
13977    1
13978    1
13979    1
13980    1
13981    1
Name: Predicted_Class, Length: 13982, dtype: int64

In [30]:
prep=result.iloc[:,2:6]

In [31]:
prep

       prob_class_1  prob_class_2  prob_class_3  prob_class_4
0          1.000000  1.557611e-11  2.003883e-24  6.429623e-23
1          1.000000  6.542828e-09  3.326383e-22  4.622985e-14
2          0.999998  2.159674e-06  6.482875e-17  7.269328e-14
3          1.000000  1.544568e-07  1.096045e-17  5.244432e-12
4          0.999998  1.994562e-06  1.202553e-14  1.162846e-07
...             ...           ...           ...           ...
13977      1.000000  5.786899e-14  7.518559e-14  1.169927e-29
13978      1.000000  1.524155e-15  2.447295e-11  2.888258e-30
13979      1.000000  1.268567e-15  1.930222e-11  1.606761e-30
13980      1.000000  9.461635e-16  1.508028e-11  1.185239e-30
13981      1.000000  4.886416e-17  2.586260e-14  1.464910e-31

[13982 rows x 4 columns]

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

precision = precision_score(exp, pre, average='macro') 

recall = recall_score(exp, pre, average='macro')

f1 = f1_score(exp, pre, average='macro')

auc = roc_auc_score(exp, prep, multi_class='ovr')
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"AUC: {auc}")

Precision: 0.9531393234576894
Recall: 0.9539182035742713
F1 Score: 0.9535227562178088
AUC: 0.9981096985866283