In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df1=pd.read_excel(r"Original_database.xlsx",sheet_name="Ti-Cs")

In [3]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):
    if not isinstance(desc, str):
        return None
    mat = np.zeros((4, 7), dtype=int)
    
    if desc.strip() == '16Cs':
        for r, c in pos_map.values():
            mat[r, c] = 1
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2 
        else:
            mat[r, c] = 1 
    return mat

df1['Matrix'] = df1['M1-M2'].apply(catalyst_to_matrix)

In [4]:
df2=pd.read_excel(r"Original_database.xlsx",sheet_name="Cs-Si")

In [5]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):
    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Si':
        for r, c in pos_map.values():
            mat[r, c] = 3
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 1  
        else:
            mat[r, c] = 3  

    return mat


df2['Matrix'] = df2['M1-M2'].apply(catalyst_to_matrix)

In [6]:
df2

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,16Si,0.000000,1,"[[3, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,1Cs15Si-1,0.000000,1,"[[1, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,2Cs14Si-1+2,0.046875,3,"[[1, 1, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,2Cs14Si-1+4,0.046875,3,"[[1, 3, 3, 1, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
4,2Cs14Si-1+5,0.046875,3,"[[1, 3, 3, 3, 0, 0, 0], [0, 1, 3, 3, 3, 0, 0],..."
...,...,...,...,...
4109,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+13+14+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4110,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4111,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4112,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
4113,15Cs1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0.000000,1,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."

In [7]:
df3=pd.read_excel(r"Original_database.xlsx",sheet_name="Ti-Si")

In [8]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):

    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Ti':
        for r, c in pos_map.values():
            mat[r, c] = 2
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2   
        else:
            mat[r, c] = 3   

    return mat


df3['Matrix'] = df3['M1-M2'].apply(catalyst_to_matrix)

In [9]:
df3

,M1-M2,Weak ratio*Moderate ratio,True Class,Matrix
0,1Ti15Si-1,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,2Ti14Si-1+2,0,1,"[[2, 2, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,2Ti14Si-1+4,0,1,"[[2, 3, 3, 2, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,2Ti14Si-1+5,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 2, 3, 3, 3, 0, 0],..."
4,2Ti14Si-1+8,0,1,"[[2, 3, 3, 3, 0, 0, 0], [0, 3, 3, 3, 2, 0, 0],..."
...,...,...,...,...
4245,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+14+15+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4246,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+15+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4247,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+16,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4248,15Ti1Si-1+2+3+4+5+6+7+8+9+10+11+12+13+14+15,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
4249,16Ti,0,1,"[[2, 2, 2, 2, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."

In [10]:
df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

In [12]:
df4=pd.read_excel(r"Ti-Cs_59917.xlsx")

In [13]:
df4

                  Position_only                             M1-M2
0                             2                         1Ti15Cs-2
1                             3                         1Ti15Cs-3
2                             4                         1Ti15Cs-4
3                             5                         1Ti15Cs-5
4                             6                         1Ti15Cs-6
...                         ...                               ...
59912       2+3+4+5+10+11+12+16        8Ti8Cs-2+3+4+5+10+11+12+16
59913  2+5+6+7+8+12+13+14+15+16  10Ti6Cs-2+5+6+7+8+12+13+14+15+16
59914        1+2+3+4+8+10+13+15         8Ti8Cs-1+2+3+4+8+10+13+15
59915         1+2+3+4+6+7+13+15          8Ti8Cs-1+2+3+4+6+7+13+15
59916         1+4+7+10+11+13+16          7Ti9Cs-1+4+7+10+11+13+16

[59917 rows x 2 columns]

In [14]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):
    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Cs':
        for r, c in pos_map.values():
            mat[r, c] = 1
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2   
        else:
            mat[r, c] = 1  

    return mat


df4['Matrix'] = df4['M1-M2'].apply(catalyst_to_matrix)

In [15]:
df4

,Position_only,M1-M2,Matrix
0,2,1Ti15Cs-2,"[[1, 2, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
1,3,1Ti15Cs-3,"[[1, 1, 2, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
2,4,1Ti15Cs-4,"[[1, 1, 1, 2, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
3,5,1Ti15Cs-5,"[[1, 1, 1, 1, 0, 0, 0], [0, 2, 1, 1, 1, 0, 0],..."
4,6,1Ti15Cs-6,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 2, 1, 1, 0, 0],..."
...,...,...,...
59912,2+3+4+5+10+11+12+16,8Ti8Cs-2+3+4+5+10+11+12+16,"[[1, 2, 2, 2, 0, 0, 0], [0, 2, 1, 1, 1, 0, 0],..."
59913,2+5+6+7+8+12+13+14+15+16,10Ti6Cs-2+5+6+7+8+12+13+14+15+16,"[[1, 2, 1, 1, 0, 0, 0], [0, 2, 2, 2, 2, 0, 0],..."
59914,1+2+3+4+8+10+13+15,8Ti8Cs-1+2+3+4+8+10+13+15,"[[2, 2, 2, 2, 0, 0, 0], [0, 1, 1, 1, 2, 0, 0],..."
59915,1+2+3+4+6+7+13+15,8Ti8Cs-1+2+3+4+6+7+13+15,"[[2, 2, 2, 2, 0, 0, 0], [0, 1, 2, 2, 1, 0, 0],..."
59916,1+4+7+10+11+13+16,7Ti9Cs-1+4+7+10+11+13+16,"[[2, 1, 1, 2, 0, 0, 0], [0, 1, 1, 2, 1, 0, 0],..."

In [20]:
df5=pd.read_excel(r"Cs-Si_61421.xlsx")

In [21]:
df5

            Position_only                      M1-M2
0                       2                  1Cs15Si-2
1                       3                  1Cs15Si-3
2                       4                  1Cs15Si-4
3                       5                  1Cs15Si-5
4                       6                  1Cs15Si-6
...                   ...                        ...
61416       4+11+12+14+15      5Cs11Si-4+11+12+14+15
61417  1+2+3+4+8+10+13+15  8Cs8Si-1+2+3+4+8+10+13+15
61418     1+2+4+5+8+10+15     7Cs9Si-1+2+4+5+8+10+15
61419   1+2+3+4+6+7+13+15   8Cs8Si-1+2+3+4+6+7+13+15
61420   1+4+7+10+11+13+16   7Cs9Si-1+4+7+10+11+13+16

[61421 rows x 2 columns]

In [22]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):

    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Si':
        for r, c in pos_map.values():
            mat[r, c] = 3
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 1  
        else:
            mat[r, c] = 3  

    return mat


df5['Matrix'] = df5['M1-M2'].apply(catalyst_to_matrix)

In [23]:
df5

,Position_only,M1-M2,Matrix
0,2,1Cs15Si-2,"[[3, 1, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,3,1Cs15Si-3,"[[3, 3, 1, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,4,1Cs15Si-4,"[[3, 3, 3, 1, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,5,1Cs15Si-5,"[[3, 3, 3, 3, 0, 0, 0], [0, 1, 3, 3, 3, 0, 0],..."
4,6,1Cs15Si-6,"[[3, 3, 3, 3, 0, 0, 0], [0, 3, 1, 3, 3, 0, 0],..."
...,...,...,...
61416,4+11+12+14+15,5Cs11Si-4+11+12+14+15,"[[3, 3, 3, 1, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
61417,1+2+3+4+8+10+13+15,8Cs8Si-1+2+3+4+8+10+13+15,"[[1, 1, 1, 1, 0, 0, 0], [0, 3, 3, 3, 1, 0, 0],..."
61418,1+2+4+5+8+10+15,7Cs9Si-1+2+4+5+8+10+15,"[[1, 1, 3, 1, 0, 0, 0], [0, 1, 3, 3, 1, 0, 0],..."
61419,1+2+3+4+6+7+13+15,8Cs8Si-1+2+3+4+6+7+13+15,"[[1, 1, 1, 1, 0, 0, 0], [0, 3, 1, 1, 3, 0, 0],..."
61420,1+4+7+10+11+13+16,7Cs9Si-1+4+7+10+11+13+16,"[[1, 3, 3, 1, 0, 0, 0], [0, 3, 3, 1, 3, 0, 0],..."

In [24]:
df6=pd.read_excel(r"Ti-Si_61285.xlsx")

In [25]:
df6

            Position_only                      M1-M2
0                       2                  1Ti15Si-2
1                       3                  1Ti15Si-3
2                       4                  1Ti15Si-4
3                       5                  1Ti15Si-5
4                       6                  1Ti15Si-6
...                   ...                        ...
61280       4+11+12+14+15      5Ti11Si-4+11+12+14+15
61281  1+2+3+4+8+10+13+15  8Ti8Si-1+2+3+4+8+10+13+15
61282     1+2+4+5+8+10+15     7Ti9Si-1+2+4+5+8+10+15
61283   1+2+3+4+6+7+13+15   8Ti8Si-1+2+3+4+6+7+13+15
61284   1+4+7+10+11+13+16   7Ti9Si-1+4+7+10+11+13+16

[61285 rows x 2 columns]

In [26]:
pos_map = {
    1:(0,0), 2:(0,1), 3:(0,2), 4:(0,3),
    5:(1,1), 6:(1,2), 7:(1,3), 8:(1,4),
    9:(2,2), 10:(2,3), 11:(2,4), 12:(2,5),
    13:(3,3), 14:(3,4), 15:(3,5), 16:(3,6)
}

def catalyst_to_matrix(desc):

    if not isinstance(desc, str):
        return None

    mat = np.zeros((4, 7), dtype=int)

    if desc.strip() == '16Ti':
        for r, c in pos_map.values():
            mat[r, c] = 2
        return mat

    m = re.search(r'-(.+)', desc)
    if m is None:
        return None

    pos_str = m.group(1)
    ti_positions = list(map(int, pos_str.split('+')))

    for i in range(1, 17):
        r, c = pos_map[i]
        if i in ti_positions:
            mat[r, c] = 2   
        else:
            mat[r, c] = 3   

    return mat

df6['Matrix'] = df6['M1-M2'].apply(catalyst_to_matrix)

In [27]:
df6

,Position_only,M1-M2,Matrix
0,2,1Ti15Si-2,"[[3, 2, 3, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
1,3,1Ti15Si-3,"[[3, 3, 2, 3, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
2,4,1Ti15Si-4,"[[3, 3, 3, 2, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
3,5,1Ti15Si-5,"[[3, 3, 3, 3, 0, 0, 0], [0, 2, 3, 3, 3, 0, 0],..."
4,6,1Ti15Si-6,"[[3, 3, 3, 3, 0, 0, 0], [0, 3, 2, 3, 3, 0, 0],..."
...,...,...,...
61280,4+11+12+14+15,5Ti11Si-4+11+12+14+15,"[[3, 3, 3, 2, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
61281,1+2+3+4+8+10+13+15,8Ti8Si-1+2+3+4+8+10+13+15,"[[2, 2, 2, 2, 0, 0, 0], [0, 3, 3, 3, 2, 0, 0],..."
61282,1+2+4+5+8+10+15,7Ti9Si-1+2+4+5+8+10+15,"[[2, 2, 3, 2, 0, 0, 0], [0, 2, 3, 3, 2, 0, 0],..."
61283,1+2+3+4+6+7+13+15,8Ti8Si-1+2+3+4+6+7+13+15,"[[2, 2, 2, 2, 0, 0, 0], [0, 3, 2, 2, 3, 0, 0],..."
61284,1+4+7+10+11+13+16,7Ti9Si-1+4+7+10+11+13+16,"[[2, 3, 3, 2, 0, 0, 0], [0, 3, 3, 2, 3, 0, 0],..."

In [28]:
df_result = pd.concat([df4, df6, df5], axis=0, ignore_index=True)

In [29]:
df_result

,Position_only,M1-M2,Matrix
0,2,1Ti15Cs-2,"[[1, 2, 1, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
1,3,1Ti15Cs-3,"[[1, 1, 2, 1, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
2,4,1Ti15Cs-4,"[[1, 1, 1, 2, 0, 0, 0], [0, 1, 1, 1, 1, 0, 0],..."
3,5,1Ti15Cs-5,"[[1, 1, 1, 1, 0, 0, 0], [0, 2, 1, 1, 1, 0, 0],..."
4,6,1Ti15Cs-6,"[[1, 1, 1, 1, 0, 0, 0], [0, 1, 2, 1, 1, 0, 0],..."
...,...,...,...
182618,4+11+12+14+15,5Cs11Si-4+11+12+14+15,"[[3, 3, 3, 1, 0, 0, 0], [0, 3, 3, 3, 3, 0, 0],..."
182619,1+2+3+4+8+10+13+15,8Cs8Si-1+2+3+4+8+10+13+15,"[[1, 1, 1, 1, 0, 0, 0], [0, 3, 3, 3, 1, 0, 0],..."
182620,1+2+4+5+8+10+15,7Cs9Si-1+2+4+5+8+10+15,"[[1, 1, 3, 1, 0, 0, 0], [0, 1, 3, 3, 1, 0, 0],..."
182621,1+2+3+4+6+7+13+15,8Cs8Si-1+2+3+4+6+7+13+15,"[[1, 1, 1, 1, 0, 0, 0], [0, 3, 1, 1, 3, 0, 0],..."
182622,1+4+7+10+11+13+16,7Cs9Si-1+4+7+10+11+13+16,"[[1, 3, 3, 1, 0, 0, 0], [0, 3, 3, 1, 3, 0, 0],..."

In [30]:
import os
import ast
import random
import numpy as np
import pandas as pd

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_DISABLE_MKL'] = '1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
from sklearn.metrics import accuracy_score
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ReduceLROnPlateau, LearningRateScheduler
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

BATCH_SIZE = 32
EPOCHS = 100
NUM_CLASSES = 4
EXPECTED_SHAPE = (4, 7)
L2 = 1e-4
DROPOUT = 0.3
INIT_LR = 1e-3

REDUCE_LR_CALLBACK = ReduceLROnPlateau(monitor='loss', factor=0.5, patience=8, min_lr=1e-6)

def create_adaptive_lr_schedule(initial_lr=INIT_LR):
    def lr_schedule(epoch):
        if epoch < 30:
            return initial_lr
        elif epoch < 60:
            return initial_lr * 0.3
        elif epoch < 80:
            return initial_lr * 0.2
        else:
            return initial_lr * 0.1
    return LearningRateScheduler(lr_schedule)

def parse_matrix_cell(cell):
    if isinstance(cell, np.ndarray):
        return cell
    if isinstance(cell, list):
        return np.array(cell)
    if isinstance(cell, (int, float)):
        return np.array([[cell]])
    if isinstance(cell, str):
        try:
            parsed = ast.literal_eval(cell)
            return np.array(parsed)
        except Exception:
            try:
                parts = [float(x) for x in cell.replace(';', ',').split(',') if x.strip() != '']
                return np.array(parts)
            except Exception:
                raise ValueError(f"Cannot parse Matrix cell: {cell[:80]}")
    raise ValueError(f"Unsupported Matrix cell type: {type(cell)}")

def dataset_to_Xy(dataset, expected_shape=EXPECTED_SHAPE):
    """Extract feature matrix and labels"""
    if 'Matrix' not in dataset.columns:
        raise KeyError("Dataset must contain 'Matrix' column")
    
    matrices = []
    for i, cell in enumerate(dataset['Matrix'].values):
        arr = parse_matrix_cell(cell)
        if arr.ndim == 1:
            if arr.size == expected_shape[0]*expected_shape[1]:
                arr = arr.reshape(expected_shape)
            else:
                raise ValueError(f"Sample {i} has incorrect size")
        elif arr.ndim == 2 and arr.shape != expected_shape:
            raise ValueError(f"Sample {i} has incorrect shape {arr.shape}")
        matrices.append(arr.astype(np.float32))
    
    X = np.stack(matrices, axis=0)[..., np.newaxis]
    
    y_raw = None
    if 'True Class' in dataset.columns:
        y_raw = dataset['True Class'].astype(int).values
    
    return X, y_raw

def build_model_improved(input_shape=(4,7), num_classes=NUM_CLASSES, dropout_rate=DROPOUT, l2_reg=L2, lr=INIT_LR):
    from tensorflow.keras.layers import Input, Conv2D, LeakyReLU, Concatenate, MaxPooling2D, GlobalAveragePooling2D, Dense, Dropout
    from tensorflow.keras.models import Model
    
    inp = Input(shape=(input_shape[0], input_shape[1], 1))
    x1 = Conv2D(96, (1,5), padding='same', kernel_regularizer=regularizers.l2(l2_reg))(inp)
    x1 = LeakyReLU(negative_slope=0.1)(x1)
    
    x2 = Conv2D(128, (1,5), padding='same', kernel_regularizer=regularizers.l2(l2_reg))(x1)
    x2 = LeakyReLU(negative_slope=0.1)(x2)
    x2 = Concatenate()([x1, x2])
    
    x3 = Conv2D(128, (1,5), padding='same', kernel_regularizer=regularizers.l2(l2_reg))(x2)
    x3 = LeakyReLU(negative_slope=0.1)(x3)
    x3 = Concatenate()([x1, x2, x3])
    
    x = MaxPooling2D((1,2))(x3)
    
    x = Conv2D(256, (2,2), padding='valid', kernel_regularizer=regularizers.l2(l2_reg))(x)
    x = LeakyReLU(negative_slope=0.1)(x)
    
    x = GlobalAveragePooling2D()(x)
    
    x = Dense(1024, kernel_regularizer=regularizers.l2(l2_reg))(x)
    x = LeakyReLU(negative_slope=0.1)(x)
    x = Dropout(dropout_rate)(x)
    
    x = Dense(512, kernel_regularizer=regularizers.l2(l2_reg))(x)
    x = LeakyReLU(negative_slope=0.1)(x)
    x = Dropout(dropout_rate)(x)
    
    out = Dense(num_classes, activation='softmax')(x)
    
    model = Model(inp, out)
    
    optimizer = Adam(learning_rate=lr, beta_1=0.9, beta_2=0.999, epsilon=1e-7)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model

def train_final_model(dataset, model_save_path="final_model.keras"):
    print("\n=== Training final model ===")
    print(f"Dataset shape: {dataset.shape}")
    
    X, y_raw = dataset_to_Xy(dataset)
    
    if y_raw is None:
        raise ValueError("Training data must contain 'True Class' column")
    
    y0 = (y_raw - 1).astype(int)
    y_cat = to_categorical(y0, num_classes=NUM_CLASSES)
    
    print(f"Training data shape: X{X.shape}, y{y_cat.shape}")
    print("Class distribution:", np.unique(y_raw, return_counts=True))
    
    model = build_model_improved()
    
    callbacks = [
        create_adaptive_lr_schedule(INIT_LR),
        REDUCE_LR_CALLBACK
    ]
    
    history = model.fit(
        X, y_cat,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        callbacks=callbacks,
        verbose=1
    )
    
    model.save(model_save_path)
    print(f"Final model saved: {model_save_path}")
    
    train_predictions = model.predict(X, verbose=0)
    train_predicted_classes = np.argmax(train_predictions, axis=1) + 1
    train_accuracy = accuracy_score(y_raw, train_predicted_classes)
    print(f"Training accuracy: {train_accuracy:.4f}")
    
    return model, history

def predict_df_result(model, df_result, output_csv="df_result_predictions.csv"):
    print("\n=== Predicting new samples ===")
    print(f"df_result shape: {df_result.shape}")
    
    if 'Matrix' not in df_result.columns:
        raise KeyError("df_result must contain 'Matrix' column")
    
    X_new, _ = dataset_to_Xy(df_result)
    print(f"Feature shape: {X_new.shape}")
    
    predictions_proba = model.predict(X_new, verbose=1)
    predicted_classes = np.argmax(predictions_proba, axis=1) + 1
    
    df_result['Predicted_Class'] = predicted_classes
    df_result['Class_1_Probability'] = predictions_proba[:, 0]
    df_result['Class_2_Probability'] = predictions_proba[:, 1]
    df_result['Class_3_Probability'] = predictions_proba[:, 2]
    df_result['Class_4_Probability'] = predictions_proba[:, 3]
    df_result['Confidence'] = np.max(predictions_proba, axis=1)
    
    df_result.to_csv(output_csv, index=False)
    print(f"Prediction saved: {output_csv}")
    
    print("\n=== Prediction summary ===")
    print(f"Total samples: {len(df_result)}")
    
    class_counts = df_result['Predicted_Class'].value_counts().sort_index()
    for class_id, count in class_counts.items():
        print(f"Class {class_id}: {count} samples ({count/len(df_result)*100:.1f}%)")
    
    print(f"Mean confidence: {df_result['Confidence'].mean():.4f}")
    
    print("\n=== First 5 predictions ===")
    preview_cols = [
        'Predicted_Class', 'Class_1_Probability',
        'Class_2_Probability', 'Class_3_Probability',
        'Class_4_Probability', 'Confidence'
    ]
    print(df_result[preview_cols].head())
    
    return df_result

if __name__ == "__main__":
    print("=== CNN Matrix Classification - Final Training & Prediction ===")
    
    try:
        print("Checking data...")
        print(f"df type: {type(df)}, shape: {df.shape}")
        print(f"df_result type: {type(df_result)}, shape: {df_result.shape}")
        
        print("\n1. Training model...")
        trained_model, history = train_final_model(df)
        
        print("\n2. Predicting...")
        result_with_predictions = predict_df_result(
            model=trained_model,
            df_result=df_result,
            output_csv=r"Prediction_result.csv"
        )
        
        print("\nPreview:")
        print(result_with_predictions[['Predicted_Class', 'Confidence']].head())
        
    except NameError as e:
        print(f"Data error: {e}")
    except Exception as e:
        print(f"Execution error: {e}")
        import traceback
        traceback.print_exc()
    
    print("\nDone.")

=== CNN Matrix Classification - Final Training & Prediction ===
Checking data...
df type: <class 'pandas.core.frame.DataFrame'>, shape: (13982, 4)
df_result type: <class 'pandas.core.frame.DataFrame'>, shape: (182623, 3)

1. Training model...

=== Training final model ===
Dataset shape: (13982, 4)
Training data shape: X(13982, 4, 7, 1), y(13982, 4)
Class distribution: (array([1, 2, 3, 4]), array([5426, 3180, 2952, 2424], dtype=int64))
Epoch 1/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 9s 17ms/step - accuracy: 0.6770 - loss: 0.8781 - learning_rate: 0.0010
Epoch 2/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.7545 - loss: 0.6467 - learning_rate: 0.0010
Epoch 3/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.7735 - loss: 0.5850 - learning_rate: 0.0010
Epoch 4/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.7940 - loss: 0.5382 - learning_rate: 0.0010
Epoch 5/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8040 - loss: 0.5170 - learning_rate: 0.0010
Epoch 6/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8200 - loss: 0.4967 - learning_rate: 0.0010
Epoch 7/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8320 - loss: 0.4635 - learning_rate: 0.0010
Epoch 8/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.8515 - loss: 0.4326 - learning_rate: 0.0010
Epoch 9/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.8562 - loss: 0.4219 - learning_rate: 0.0010
Epoch 10/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.8665 - loss: 0.4061 - learning_rate: 0.0010
Epoch 11/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8748 - loss: 0.3899 - learning_rate: 0.0010
Epoch 12/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8848 - loss: 0.3683 - learning_rate: 0.0010
Epoch 13/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.8906 - loss: 0.3652 - learning_rate: 0.0010
Epoch 14/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.8941 - loss: 0.3539 - learning_rate: 0.0010
Epoch 15/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9026 - loss: 0.3407 - learning_rate: 0.0010
Epoch 16/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9067 - loss: 0.3392 - learning_rate: 0.0010
Epoch 17/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9084 - loss: 0.3269 - learning_rate: 0.0010
Epoch 18/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9144 - loss: 0.3189 - learning_rate: 0.0010
Epoch 19/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9205 - loss: 0.3072 - learning_rate: 0.0010
Epoch 20/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9218 - loss: 0.3052 - learning_rate: 0.0010
Epoch 21/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9264 - loss: 0.2989 - learning_rate: 0.0010
Epoch 22/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9275 - loss: 0.2922 - learning_rate: 0.0010
Epoch 23/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9311 - loss: 0.2847 - learning_rate: 0.0010
Epoch 24/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9359 - loss: 0.2727 - learning_rate: 0.0010
Epoch 25/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9323 - loss: 0.2807 - learning_rate: 0.0010
Epoch 26/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9333 - loss: 0.2807 - learning_rate: 0.0010
Epoch 27/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9408 - loss: 0.2669 - learning_rate: 0.0010
Epoch 28/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9424 - loss: 0.2596 - learning_rate: 0.0010
Epoch 29/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9411 - loss: 0.2679 - learning_rate: 0.0010
Epoch 30/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9451 - loss: 0.2530 - learning_rate: 0.0010
Epoch 31/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9645 - loss: 0.2029 - learning_rate: 3.0000e-04
Epoch 32/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9660 - loss: 0.1921 - learning_rate: 3.0000e-04
Epoch 33/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9663 - loss: 0.1871 - learning_rate: 3.0000e-04
Epoch 34/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9657 - loss: 0.1799 - learning_rate: 3.0000e-04
Epoch 35/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9663 - loss: 0.1756 - learning_rate: 3.0000e-04
Epoch 36/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9671 - loss: 0.1730 - learning_rate: 3.0000e-04
Epoch 37/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9677 - loss: 0.1670 - learning_rate: 3.0000e-04
Epoch 38/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9694 - loss: 0.1657 - learning_rate: 3.0000e-04
Epoch 39/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9684 - loss: 0.1614 - learning_rate: 3.0000e-04
Epoch 40/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9681 - loss: 0.1618 - learning_rate: 3.0000e-04
Epoch 41/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9695 - loss: 0.1581 - learning_rate: 3.0000e-04
Epoch 42/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9695 - loss: 0.1577 - learning_rate: 3.0000e-04
Epoch 43/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9714 - loss: 0.1550 - learning_rate: 3.0000e-04
Epoch 44/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9670 - loss: 0.1570 - learning_rate: 3.0000e-04
Epoch 45/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9695 - loss: 0.1519 - learning_rate: 3.0000e-04
Epoch 46/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9692 - loss: 0.1535 - learning_rate: 3.0000e-04
Epoch 47/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9675 - loss: 0.1512 - learning_rate: 3.0000e-04
Epoch 48/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9703 - loss: 0.1471 - learning_rate: 3.0000e-04
Epoch 49/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9695 - loss: 0.1470 - learning_rate: 3.0000e-04
Epoch 50/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9704 - loss: 0.1483 - learning_rate: 3.0000e-04
Epoch 51/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9687 - loss: 0.1486 - learning_rate: 3.0000e-04
Epoch 52/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9703 - loss: 0.1442 - learning_rate: 3.0000e-04
Epoch 53/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9717 - loss: 0.1411 - learning_rate: 3.0000e-04
Epoch 54/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9695 - loss: 0.1450 - learning_rate: 3.0000e-04
Epoch 55/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9739 - loss: 0.1357 - learning_rate: 3.0000e-04
Epoch 56/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9676 - loss: 0.1429 - learning_rate: 3.0000e-04
Epoch 57/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9706 - loss: 0.1396 - learning_rate: 3.0000e-04
Epoch 58/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9690 - loss: 0.1399 - learning_rate: 3.0000e-04
Epoch 59/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9697 - loss: 0.1394 - learning_rate: 3.0000e-04
Epoch 60/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9710 - loss: 0.1369 - learning_rate: 3.0000e-04
Epoch 61/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9716 - loss: 0.1298 - learning_rate: 2.0000e-04
Epoch 62/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9723 - loss: 0.1299 - learning_rate: 2.0000e-04
Epoch 63/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9728 - loss: 0.1264 - learning_rate: 2.0000e-04
Epoch 64/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9741 - loss: 0.1253 - learning_rate: 2.0000e-04
Epoch 65/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9746 - loss: 0.1236 - learning_rate: 2.0000e-04
Epoch 66/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9739 - loss: 0.1236 - learning_rate: 2.0000e-04
Epoch 67/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9738 - loss: 0.1239 - learning_rate: 2.0000e-04
Epoch 68/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 18ms/step - accuracy: 0.9750 - loss: 0.1234 - learning_rate: 2.0000e-04
Epoch 69/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9734 - loss: 0.1219 - learning_rate: 2.0000e-04
Epoch 70/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9738 - loss: 0.1229 - learning_rate: 2.0000e-04
Epoch 71/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9736 - loss: 0.1213 - learning_rate: 2.0000e-04
Epoch 72/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9744 - loss: 0.1212 - learning_rate: 2.0000e-04
Epoch 73/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9730 - loss: 0.1198 - learning_rate: 2.0000e-04
Epoch 74/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9740 - loss: 0.1216 - learning_rate: 2.0000e-04
Epoch 75/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9749 - loss: 0.1198 - learning_rate: 2.0000e-04
Epoch 76/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9740 - loss: 0.1187 - learning_rate: 2.0000e-04
Epoch 77/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9740 - loss: 0.1194 - learning_rate: 2.0000e-04
Epoch 78/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9758 - loss: 0.1151 - learning_rate: 2.0000e-04
Epoch 79/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9738 - loss: 0.1165 - learning_rate: 2.0000e-04
Epoch 80/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9769 - loss: 0.1149 - learning_rate: 2.0000e-04
Epoch 81/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 18ms/step - accuracy: 0.9768 - loss: 0.1118 - learning_rate: 1.0000e-04
Epoch 82/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9779 - loss: 0.1074 - learning_rate: 1.0000e-04
Epoch 83/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 18ms/step - accuracy: 0.9781 - loss: 0.1091 - learning_rate: 1.0000e-04
Epoch 84/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9788 - loss: 0.1069 - learning_rate: 1.0000e-04
Epoch 85/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9793 - loss: 0.1054 - learning_rate: 1.0000e-04
Epoch 86/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9813 - loss: 0.1037 - learning_rate: 1.0000e-04
Epoch 87/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9795 - loss: 0.1050 - learning_rate: 1.0000e-04
Epoch 88/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9800 - loss: 0.1057 - learning_rate: 1.0000e-04
Epoch 89/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9800 - loss: 0.1028 - learning_rate: 1.0000e-04
Epoch 90/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.9789 - loss: 0.1040 - learning_rate: 1.0000e-04
Epoch 91/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9812 - loss: 0.1020 - learning_rate: 1.0000e-04
Epoch 92/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9813 - loss: 0.1024 - learning_rate: 1.0000e-04
Epoch 93/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9817 - loss: 0.1005 - learning_rate: 1.0000e-04
Epoch 94/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9807 - loss: 0.1003 - learning_rate: 1.0000e-04
Epoch 95/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 8s 18ms/step - accuracy: 0.9808 - loss: 0.0998 - learning_rate: 1.0000e-04
Epoch 96/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9836 - loss: 0.0969 - learning_rate: 1.0000e-04
Epoch 97/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9814 - loss: 0.0998 - learning_rate: 1.0000e-04
Epoch 98/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9818 - loss: 0.0985 - learning_rate: 1.0000e-04
Epoch 99/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9814 - loss: 0.0999 - learning_rate: 1.0000e-04
Epoch 100/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9833 - loss: 0.0972 - learning_rate: 1.0000e-04
Final model saved: final_model.keras
Training accuracy: 0.9866

2. Predicting...

=== Predicting new samples ===
df_result shape: (182623, 3)
Feature shape: (182623, 4, 7, 1)
5707/5707 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step
Prediction saved: Prediction_result.csv

=== Prediction summary ===
Total samples: 182623
Class 1: 64268 samples (35.2%)
Class 2: 57767 samples (31.6%)
Class 3: 35986 samples (19.7%)
Class 4: 24602 samples (13.5%)
Mean confidence: 0.9689

=== First 5 predictions ===
   Predicted_Class  Class_1_Probability  Class_2_Probability  \
0                1                  1.0         3.990185e-07
1                1                  1.0         2.110304e-07
2                1                  1.0         1.537379e-07
3                1                  1.0         6.833278e-11
4                1                  1.0         3.997251e-11

   Class_3_Probability  Class_4_Probability  Confidence
0         1.567348e-18         1.782076e-12         1.0
1         1.276492e-18         1.098919e-12         1.0
2         4.881305e-19         6.555468e-13         1.0
3         2.040931e-22         3.226954e-16         1.0
4         3.351833e-22         2.016867e-16         1.0

Preview:
   Predicted_Class  Confidence
0                1         1.0
1                1         1.0
2                1         1.0
3                1         1.0
4                1         1.0

Done.